[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "Categories"
pageRef = "categories"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 30

[[main]]
name = "About Me"
pageRef = "posts"
identifier = "SkGpqzP4xU"
weight = 9999

[[footer]]
none = "none"
